template: |
  ## :books: Changes since last version

  $CHANGES

  ##### :clap: Many thanks to everyone who participated in this release :point_down:
  $CONTRIBUTORS

replacers:
  - search: '/BB-(\d+)/g'
    replace: 'https://tickets.metabrainz.org/browse/BB-$1'

categories:
  - title: ':boom: Breaking Changes'
    label: 'major'
  - title: '🚂 New features and bug fixes'
  - title: ':wrench: Maintenance'
    collapse-after: 3
    labels:
      - 'dependencies'

exclude-contributors:
  - 'dependabot'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
  
  name-template: 'v$RESOLVED_VERSION'
  tag-template: 'v$RESOLVED_VERSION'